services:
  load-balancer:
    build:
      context: ./LoadBalancerService
      dockerfile: Dockerfile.${BUILD_ENV:-development}
    environment:
      BUILD_ENV: development
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public-network
  gateway:
    build: ./GatewayService
    ports:
      - "5000:5000"
    depends_on:
      - load-balancer
    networks:
      - public-network
      - private-network
  auth:
    build: ./AuthService
    ports:
      - "3000:3000"
    # environment:
    #   - MONGO_URL=mongodb://auth_mongo:27017/micro_authdb
    depends_on:
      - gateway
      # - kafka
    networks:
      - private-network


networks:
  public-network:
  private-network:
