# Base image
FROM nginx

# Copy nginx configuration
COPY nginx_dev.conf /etc/nginx/nginx.conf

# Set environment variable
ENV NODE_ENV=development

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
